services:
  db:
    image: postgres:16
    container_name: slabforge_db
    environment:
      POSTGRES_USER: slabforge
      POSTGRES_PASSWORD: slabforge
      POSTGRES_DB: slabforge
    ports:
      - "5433:5432"
    volumes:
      - slabforge_pgdata:/var/lib/postgresql/data

volumes:
  slabforge_pgdata:
